/*---- EXERCISE 3 (EXPLANATION) ----*/

// Array of students

let students = [
  {
    name: "Alejandro",
    lastName: "Martinez",
    grade: "5 GCSES",
    subjects: {
      mathematics: 6,
      english: 5,
      geography: 7,
      economy: 5.5,
      philosophy: 7,
      spanish: 8,
      history: 7,
      art: 5,
    },
  },
  {
    name: "Alberto",
    lastName: "Rossi",
    grade: "5 GCSES",
    subjects: {
      mathematics: 4,
      english: 5,
      geography: 6,
      economy: 3,
      philosophy: 2,
      spanish: 2,
      history: 4,
      art: 5,
    },
  },
  {
    name: "Ana",
    lastName: "Pascual",
    grade: "5 GCSES",
    subjects: {
      mathematics: 1,
      english: 8,
      geography: 6,
      economy: 3,
      philosophy: 7,
      spanish: 5,
      history: 5,
      art: 8,
    },
  },
  {
    name: "Alberto",
    lastName: "Lozano",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 6,
      geography: 4,
      economy: 3,
      philosophy: 7,
      spanish: 6,
      history: 5,
      art: 5,
    },
  },
  {
    name: "Enrique",
    lastName: "Martin",
    grade: "5 GCSES",
    subjects: {
      mathematics: 5,
      english: 6,
      geography: 5,
      economy: 3,
      philosophy: 7,
      spanish: 6,
      history: 5,
      art: 6,
    },
  },
  {
    name: "Marina",
    lastName: "Martinez",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 7,
      geography: 8,
      economy: 7,
      philosophy: 7,
      spanish: 9,
      history: 8,
      art: 7,
    },
  },
  {
    name: "Carla",
    lastName: "Peral",
    grade: "5 GCSES",
    subjects: {
      mathematics: 5,
      english: 6,
      geography: 5,
      economy: 6,
      philosophy: 7,
      spanish: 4,
      history: 5,
      art: 2,
    },
  },
  {
    name: "Jesus",
    lastName: "Haro",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 6,
      geography: 3,
      economy: 4,
      philosophy: 7,
      spanish: 5,
      history: 6,
      art: 7,
    },
  },
  {
    name: "Roberto",
    lastName: "Leal",
    grade: "5 GCSES",
    subjects: {
      mathematics: 2,
      english: 5,
      geography: 5,
      economy: 6,
      philosophy: 5,
      spanish: 6,
      history: 4,
      art: 3,
    },
  },
  {
    name: "Jorge",
    lastName: "Hermoso",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 6,
      geography: 4,
      economy: 7,
      philosophy: 7,
      spanish: 6,
      history: 5,
      art: 6,
    },
  },
  {
    name: "Laura",
    lastName: "Romero",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 6,
      geography: 5,
      economy: 8,
      philosophy: 7,
      spanish: 6,
      history: 5,
      art: 5,
    },
  },
  {
    name: "Paco",
    lastName: "Gil",
    grade: "5 GCSES",
    subjects: {
      mathematics: 8,
      english: 4,
      geography: 4,
      economy: 3,
      philosophy: 3,
      spanish: 4,
      history: 3,
      art: 5,
    },
  },
];
console.warn("Original array of students");
console.log(students);
